# -*- coding: utf-8 -*-
"""4110E007.1004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K6ZJq7DRrudL2IrNgVsbPotT1BYA1Ohw
"""

x = input('Enter the name:')
print('Hello,'+ x)

a = input("請輸入:")

a,b = eval(input("請輸入兩個數位: "))
a,b

a = "Hello, World!"
print(a[0:7])

#python strings
a = " Hello, World! "
print(a.strip()) # returns "Hello, World!"

#python strings
a = """Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."""
print(a)

#python strings
txt = "The best things in life are free!"
print("expensive" not in txt)

#python strings
txt = "The best things in life are free!"
if "expensive" not in txt:
  print("No, 'expensive' is NOT present.")

#python strings
for x in "banana":
  print(x)

#python lists
thislist = ["apple", "banana", "cherry"]
print(thislist)

#python lists
thislist = ["apple", "banana", "cherry", "apple", "cherry"]
print(thislist)

#python lists
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:5])

#python lists
thislist = ["apple", "banana", "cherry"]
if "apple" in thislist:
  print("Yes, 'apple' is in the fruits list")

#python lists
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
thislist[1:3] = ["blackcurrant", "watermelon"]
print(thislist)

#python dictionaries
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

#python dictionaries
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(type(thisdict))

#python dictionaries
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.values()

print(x) #before the change

car["year"] = 2020

print(x) #after the change

#python dictionaries
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
x = thisdict["model"]

#python dictionaries
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["color"] = "red"
print(thisdict)

#python
x = int(1)   # x will be 1
y = int(2.8) # y will be 2
z = int("3") # z will be 3

#python
thistuple = ("apple", "banana", "cherry")
print(len(thistuple))

#python
thistuple = ("apple",)
print(type(thistuple))

#NOT a tuple
thistuple = ("apple")
print(type(thistuple))

#python
tuple1 = ("abc", 34, True, 40, "male")

#python
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[3:5])